Use JSON.awk callbacks

diff --git a/jawk b/jawk
--- a/jawk
+++ b/jawk
@@ -47,123 +47,129 @@ done
 if [ ! "$p" ]; then usage; fi
 if [ ! "$f" ]; then file=-; fi
 
-pre='
-BEGIN { RS=""; FS="\n"; JSON="\1"; TYPE="\2" }
-function keys(ks, o, n, a, i) {
-	# differentiate between the root object and an empty root key
-	# if the root object
-	if (o == "" && o == 0) {
-		# if object
-		if ("\3" in _) {
-			n = split(_["\3"], a, "\037")
-			while (++i <= n) ks[a[i]] = a[i]
-		# if array
-		} else {
-			n = _["length"]
-			while (++i <= _["length"]) ks[i] = i
-		}
-	}
-	else {
-		# if object
-		if ((o SUBSEP "\3") in _) {
-			n = split(_[o,"\3"], a, "\037")
-			while (++i <= n) ks[a[i]] = o SUBSEP a[i]
-		# if array
-		} else {
-			n = _[o,"length"]
-			while (++i <= n) ks[i] = o SUBSEP i
-		}
-	}
-	return n
-}
-function __jawk(i, kv, key, value, raw_value, type, arg, cmd, ret, j) {
-	for (i = 1; i <= NF; i++) {
-		split($i, kv, "\t")
-		# remove surrounding quotes
-		key = substr(kv[1], 2, length(kv[1]) - 2)
-		value = kv[2]
-		raw_value = value
-		# if string
-		if (match(value, /^"/)) {
-			# remove surrounding quotes
-			value = substr(value, 2, length(value) - 2)
-			# check if it needs escaping
-			if (match(value, /\\/)) {
-				# unescape common characters
-				gsub(/\\"/, "\"", value)
-				gsub(/\\n/, "\n", value)
-				# if still needs escaping, fallback to printf
-				if (match(value, /\\/)) {
-					arg = raw_value
-					# double up backslashes for printf
-					gsub(/\\/, "\\\\", arg)
-					# undo for quotes
-					gsub(/\\"/, "\"", arg)
-					gsub(/`/, "\\`", arg)
-					gsub(/\$/, "\\$", arg)
-					cmd="printf %b "arg
-					value=""
-					# RS needs to be reset for getline to
-					# handle blank lines propertly
-					RS="\n"
-					while (ret = cmd | getline v) {
-						if (ret == -1)
-							exit 1
-						++j
-						if (j == 1)
-							value = v
-						else
-							value = value "\n" v
-					}
-					close(cmd)
-					RS=""
-					# if had trailing newline, add it
-					if (match(raw_value, /(^|[^\\])(\\\\)*\\n"$/))
-						value = value "\n"
-				}
-			}
-			type = "string"
-		}
-		# if object
-		else if (match(value, /^\{/)) {
-			value = key
-			type = "object"
-		}
-		# if array
-		else if (match(value, /^\[/)) {
-			value = key
-			type = "array"
-		}
-		else if (value == "true") {
-			value = 1
-			type = "boolean"
-		}
-		else if (value == "false") {
-			value = 0
-			type = "boolean"
-		}
-		else if (value == "null") {
-			value = ""
-			type = "null"
-		} else {
-			type = "number"
-		}
-		# if not the root object
-		if (kv[1]) {
-			_[key] = value
-			_[key,JSON] = raw_value
-			_[key,TYPE] = type
-		} else {
-			if (type != "array" && type != "object")
-				_[0] = value;
-			_[JSON] = raw_value
-			_[TYPE] = type
-		}
-	}
-}
-{ __jawk() }
-'
+cbs='
+# Default callbacks.
+# Mawk must always define all callbacks.
+# Gawk and busybox awk must define callbacks when STREAM=1 only.
+# More info in FAQ.md#5.
 
+# cb_parse_array_empty - parse an empty JSON array.
+# Called in JSON.awk main loop when STREAM=0 only.
+# This example returns the standard representation of an empty array.
+function cb_parse_array_empty(jpath) {
+
+#	print "parse_array_empty("jpath")" >"/dev/stderr"
+	return "[]"
+}
+
+# cb_parse_object_empty - parse an empty JSON object.
+# Called in JSON.awk main loop when STREAM=0 only.
+# This example returns the standard representation of an empty object.
+function cb_parse_object_empty(jpath) {
+
+#	print "parse_object_empty("jpath")" >"/dev/stderr"
+	return "{}"
+}
+
+# cb_parse_array_enter - begin parsing an array.
+# Called in JSON.awk main loop when STREAM=0 only.
+# Use this function to initialize or output other values involved in
+# processing each new JSON array.
+function cb_parse_array_enter(jpath) {
+
+#	print "cb_parse_array_enter("jpath") token("TOKEN")" >"/dev/stderr"
+	if ("" != jpath)
+		;
+}
+
+# cb_parse_array_exit - end parsing an array.
+# Called in JSON.awk main loop when STREAM=0 only.
+# If status == 0 then global CB_VALUE holds the JSON text of the parsed array.
+function cb_parse_array_exit(jpath, status) {
+
+#	print "cb_parse_array_exit("jpath") status("status") token("TOKEN") value("CB_VALUE")" >"/dev/stderr"
+}
+
+# cb_parse_object_enter - begin parsing an object.
+# Called in JSON.awk main loop when STREAM=0 only.
+# Use this function to initialize or output other values involved in
+# processing each new JSON object.
+function cb_parse_object_enter(jpath) {
+
+#	print "cb_parse_object_enter("jpath") token("TOKEN")" >"/dev/stderr"
+	if ("" != jpath)
+		;
+}
+
+# cb_parse_object_exit - end parsing an object.
+# Called in JSON.awk main loop when STREAM=0 only.
+# If status == 0 then global CB_VALUE holds the JSON text of the parsed object.
+function cb_parse_object_exit(jpath, status) {
+
+#	print "cb_parse_object_exit("jpath") status("status") token("TOKEN") value("CB_VALUE")" >"/dev/stderr"
+}
+
+# cb_append_jpath_component - format jpath components
+# Called in JSON.awk main loop when STREAM=0 only.
+# This example formats jpaths exactly as JSON.awk does when STREAM=1.
+function cb_append_jpath_component (jpath, component) {
+	# if it is an array index, make it 1-indexed
+	if (match(component, /^[0-9]+$/))
+		component++;
+	if (component == "") return jpath
+	gsub(/^"|"$/, "", component)
+	if (jpath == "") return "\"" component "\""
+	gsub(/^"|"$/, "", jpath)
+	return "\"" jpath SUBSEP component "\""
+}
+
+# cb_append_jpath_value - format a jpath / value pair
+# Called in JSON.awk main loop when STREAM=0 only.
+# This example formats the jpath / value pair exactly as JSON.awk does when
+# STREAM=1.
+function cb_append_jpath_value (jpath, value) {
+
+#	print "cb_append_jpath_value("jpath") ("jpath") value("value")" >"/dev/stderr"
+	return sprintf("%s\t%s", jpath, value)
+}
+
+# cb_jpaths - process cb_append_jpath_value outputs
+# Called in JSON.awk main loop when STREAM=0 only.
+# This example illustrates printing jpaths to stdout as JSON.awk does when STREAM=1.
+# See also cb_parse_array_enter and cb_parse_object_enter.
+function cb_jpaths (ary, size,   i) {
+	# Print ary - array of size jpaths and their values.
+	for(i=1; i <= size; i++) {
+		print ary[i]
+	}
+
+	# Print a newline for newline-delimited JSON
+	print ""
+}
+
+# cb_fails - process all error messages at once after parsing
+# has completed. Called in JSON.awk END action when STREAM=0 only.
+# This example illustrates printing parsing errors to stdout,
+function cb_fails (ary, size,   k) {
+
+	# Print ary - associative array of parsing failures.
+	# ary keys are the size input file names that JSON.awk read.
+	for(k in ary) {
+		print "cb_fails: invalid input file:", k
+		print FAILS[k]
+	}
+}
+
+# cb_fail1 - process a single parse error as soon as it is
+# encountered.  Called in JSON.awk main loop when STREAM=0 only.
+# Return non-zero to let JSON.awk also print the message to stderr.
+# This example illustrates printing the error message to stdout only.
+function cb_fail1 (message) {
+
+	print "cb_fail1: invalid input file:", FILENAME
+	print message
+}
+'
 parser='
 #!/usr/bin/awk -f
 #
@@ -254,11 +260,7 @@ function append_jpath_component(jpath, component) { #{{{1
 	if (0 == STREAM) {
 		return cb_append_jpath_component(jpath, component)
 	} else {
-		if (component == "") return jpath
-		gsub(/^"|"$/, "", component)
-		if (jpath == "") return "\"" component "\""
-		gsub(/^"|"$/, "", jpath)
-		return "\"" jpath SUBSEP component "\""
+		return (jpath != "" ? jpath "," : "") component
 	}
 }
 
@@ -266,7 +268,7 @@ function append_jpath_value(jpath, value) { #{{{1
 	if (0 == STREAM) {
 		return cb_append_jpath_value(jpath, value)
 	} else {
-		return sprintf("%s\t%s", jpath, value)
+		return sprintf("[%s]\t%s", jpath, value)
 	}
 }
 
@@ -299,7 +301,7 @@ function parse_array_exit(jpath, status) { #{{{1
 }
 
 function parse_array(a1,   idx,ary,jpath,ret,x) { #{{{1
-	idx=1
+	idx=0
 	ary=""
 	get_token()
 #	print "parse_array(" a1 ") TOKEN=" TOKEN >"/dev/stderr"
@@ -329,7 +331,7 @@ function parse_array(a1,   idx,ary,jpath,ret,x) { #{{{1
 	}
 
 	jpath = append_jpath_component(a1, "\"length\"")
-	x = append_jpath_value(jpath, idx-1)
+	x = append_jpath_value(jpath, idx)
 	if(0 == STREAM) {
 		# save jpath+value for cb_jpaths
 		JPATHS[++NJPATHS] = x
@@ -536,5 +538,122 @@ function tokenize(a1,   pq,pb,ESCAPE,CHAR,STRING,NUMBER,KEYWORD,SPACE) { #{{{1
 
 # vim:fdm=marker:
 '
+jawk='
+BEGIN { RS=""; FS="\n"; JSON="\1"; TYPE="\2" }
+function keys(ks, o, n, a, i) {
+	# differentiate between the root object and an empty root key
+	# if the root object
+	if (o == "" && o == 0) {
+		# if object
+		if ("\3" in _) {
+			n = split(_["\3"], a, "\037")
+			while (++i <= n) ks[a[i]] = a[i]
+		# if array
+		} else {
+			n = _["length"]
+			while (++i <= _["length"]) ks[i] = i
+		}
+	}
+	else {
+		# if object
+		if ((o SUBSEP "\3") in _) {
+			n = split(_[o,"\3"], a, "\037")
+			while (++i <= n) ks[a[i]] = o SUBSEP a[i]
+		# if array
+		} else {
+			n = _[o,"length"]
+			while (++i <= n) ks[i] = o SUBSEP i
+		}
+	}
+	return n
+}
+function __jawk(i, kv, key, value, raw_value, type, arg, cmd, ret, j) {
+	for (i = 1; i <= NF; i++) {
+		split($i, kv, "\t")
+		# remove surrounding quotes
+		key = substr(kv[1], 2, length(kv[1]) - 2)
+		value = kv[2]
+		raw_value = value
+		# if string
+		if (match(value, /^"/)) {
+			# remove surrounding quotes
+			value = substr(value, 2, length(value) - 2)
+			# check if it needs escaping
+			if (match(value, /\\/)) {
+				# unescape common characters
+				gsub(/\\"/, "\"", value)
+				gsub(/\\n/, "\n", value)
+				# if still needs escaping, fallback to printf
+				if (match(value, /\\/)) {
+					arg = raw_value
+					# double up backslashes for printf
+					gsub(/\\/, "\\\\", arg)
+					# undo for quotes
+					gsub(/\\"/, "\"", arg)
+					gsub(/`/, "\\`", arg)
+					gsub(/\$/, "\\$", arg)
+					cmd="printf %b "arg
+					value=""
+					# RS needs to be reset for getline to
+					# handle blank lines propertly
+					RS="\n"
+					while (ret = cmd | getline v) {
+						if (ret == -1)
+							exit 1
+						++j
+						if (j == 1)
+							value = v
+						else
+							value = value "\n" v
+					}
+					close(cmd)
+					RS=""
+					# if had trailing newline, add it
+					if (match(raw_value, /(^|[^\\])(\\\\)*\\n"$/))
+						value = value "\n"
+				}
+			}
+			type = "string"
+		}
+		# if object
+		else if (match(value, /^\{/)) {
+			value = key
+			type = "object"
+		}
+		# if array
+		else if (match(value, /^\[/)) {
+			value = key
+			type = "array"
+		}
+		else if (value == "true") {
+			value = 1
+			type = "boolean"
+		}
+		else if (value == "false") {
+			value = 0
+			type = "boolean"
+		}
+		else if (value == "null") {
+			value = ""
+			type = "null"
+		} else {
+			type = "number"
+		}
+		# if not the root object
+		if (kv[1]) {
+			_[key] = value
+			_[key,JSON] = raw_value
+			_[key,TYPE] = type
+		} else {
+			if (type != "array" && type != "object")
+				_[0] = value;
+			_[JSON] = raw_value
+			_[TYPE] = type
+		}
+	}
+}
+{ __jawk() }
+'
 
-awk -v BRIEF=0 -v KEYS="\3" "$parser" "$file" | awk "$@" "$pre""$prog"
+awk -v BRIEF=0 -v STREAM=0 -v KEYS="\3" "$cbs""$parser" "$file" | \
+awk "$@" "$jawk""$prog"
